version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: gateway
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_password
    ports:
      - "5432:5432"
    volumes:
      - ./env/data:/var/lib/postgresql/data
  crop-db:
    image: postgres:16-alpine
    container_name: postgres_crop_db
    environment:
      POSTGRES_DB: crop
      POSTGRES_USER: crop_user
      POSTGRES_PASSWORD: crop_password
    ports:
      - "5433:5432"
    volumes:
      - ./env/crop/data:/var/lib/postgresql/data
  cattle-db:
    image: postgres:16-alpine
    container_name: postgres_cattle_db
    environment:
      POSTGRES_DB: cattle
      POSTGRES_USER: cattle_user
      POSTGRES_PASSWORD: cattle_password
    ports:
      - "5434:5432"
    volumes:
      - ./env/cattle/data:/var/lib/postgresql/data
  commodities-db:
    image: postgres:16-alpine
    container_name: postgres_commodities_db
    environment:
      POSTGRES_DB: commodities
      POSTGRES_USER: commodities_user
      POSTGRES_PASSWORD: commodities_password
    ports:
      - "5435:5432"
    volumes:
      - ./env/commodities/data:/var/lib/postgresql/data
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8090:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true