spring:
  application:
    name: farm-bff
  logging:
    level: info
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/gateway}
    username: ${DATASOURCE_USER:gateway_user}
    password: ${DATASOURCE_PASSWORD:gateway_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:data/changelog.yml
  mvc:
    log-request-details: true

app:
  name: ${APP_NAME:antropov-farm}
  jwt:
    secret: ${JWT_SECRET:Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=}
    lifetime: ${JWT_LIFETIME:P1D}
